SELECT TOP (1000) [student_id]
      ,[first_name]
      ,[last_name]
      ,[birth_date]
      ,[login]
      ,[section_id]
      ,[year_result]
      ,[course_id]
  FROM [dbslide].[dbo].[student]
 
