CREATE TABLE T_VOITURE_VTR (
    VTR_ID            INTEGER    NOT NULL PRIMARY KEY,
   

    VTR_IMMATRICUL    CHAR(10)   NOT NULL UNIQUE,
    
    VTR_CARBURANT     CHAR(2)    NOT NULL DEFAULT 'ES'
                                 CHECK(VTR_CARBURANT IN ('ES','GO','PL')),
   

    VTR_PUISSANCE_FISC  INTEGER  NOT NULL CHECK(VTR_PUISSANCE_FISC BETWEEN 1 AND 20),
  

    VTR_NB_PLACES     INTEGER    NOT NULL CHECK(VTR_NB_PLACES BETWEEN 1 AND 7),
  